language: go
env:
- GO111MODULE=on
deploy:
  provider: releases
  api_key:
    secure: pxBAARtxHc9Sodfi3fETd/6vC1aarsU0YK+bxORNPgE9Fx1uXgemQZ1SRuQnpRLG/zNiP/1ZP/W9xI9Lmk2NGaUl/SZHZr0JqV6Pc4tmL6sZtDTc/AQS2TZD/5sP8WbM+hxYmOAA1WFpJsHJ9eiqx4LHqVBz/C1Pe/MjMWJh5qIEzyGnBHl4GIg70+vzsjLVosCJ83132UuRHBh/+vL8WkWscX+QlaLNcKSms9yoWr064VjXAj9OUI4J1XCF3de66KvzXUdW6tysAu1+WDY6Y3M2/s4wDK2yE2wzfdtI6Yv3cV3yinbcSB2zWxqJ1S1lmZ8/Y2ZY9apuraTaf2OFBy7boVggawHU610FT/O0BPP2ZVb/OL/z1Cs5Fg1fhfqx6m8k8/IOJxils9y1GIdnBxteKdahoIZhmihdIjVcb19mO8wFm7Oyv20Ny1yMj4wg38OPEynpBCpu4oWY6IsskCrbl1+70s33Mbl9xc4HSh4fDY8ZJFWwVofKspdI09rI189MnUpsJcN5FkdPuZ1rjut3SOJq3XGHBMO6OrIyYsHE6uUmW9eelflUP/QzILxiGrt/1MOQ+6PutQeXJysXsHx+sA+Y4A/L3ynOcMnzUvsrOPlVSAoxeaum6ElzPs378IYYzOt1cahX9+/PyI+w3S7sksfoSOSq+jBihRR6Ddw=
  file: builds/*
  on:
    repo: Kaurin/megantory
    branch: cicd
