language: go
env:
- GO111MODULE=on
deploy:
  provider: releases
  api_key:
    secure: SC13mSERbq5SR0uglS6cjOM/OW4tl08tQJqi4e/aO/jGLzxcESYBeAk2C40OhqFnl7xELigMpP4fYXpxF7ljxhLowfL+Vj48z4II53nUPG/sgikay0NsXmRCplFal/PQCo9IWorwC/SYxZk3A0D3wQ+wk+shHM7PxADJj8crmc+fsToJLtAnqCABm4RsjcDcP6E8RujgEgehs/x2E/ilnldIujMc1HbF8pScL0vXzT4uu7rbtCQlgewg1Sn661A8ikRi3AiZuyBaDClhY3MlHsWbd871N4JBsppFQ8D+j160fNtuv8f5iaQJj1dWExubUEmOfHJi20t8jOk36xarC6BWNTo1WCOgM6FCc23Jyta3nK0F71e+mTHuHJIJoP7PhWhy7PYGGh0uc1Lp9gneYjwIBuCZgClJWnqPKWY2ulKhv93jkGpARgYB4MfP1QLcIJdkQrHvX4N9j7qrHC+/Cb5ftfhu9IMCz0DxMMCnnaTc9Se0tXIv5JTktm/NQghOkegUcCBeeVRJuSsrkF0P5QLiTzaUQIYLdIZwd/IpyyeFZWgbo+7URJ2/Ln+44lmp9zOvYH1dQb8Sx5Jv42bAvVoRKGS+kmgrlfxFRSAt/vw1kVAn8M7AOI2CmW/HsvZ2IawDKlReY5G7R8UmGPiWYKqF+r6CYvGSZoINBSvWbhI=
  file: builds/*
  on:
    repo: Kaurin/megantory
    branch: cicd
    tags: true
