os: linux
dist: focal
group: edge
arch: arm64-graviton2
language: go
go:
- 1.16.2
after_success: test -n "$TRAVIS_TAG" && make bmacos bwindows
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: dJfgxqBN+tJn0kzT4Wii9oF7yMUMvbn2a1Auszwjz0ifkbFs5cD8N5QeedCDI+O4zrFLeLKTKwae93cbGTY/8JsBncFje5VdbmbirdkEPFTeScYtjG+bL/EGjprECqmXxOPg/e4YbEhzI9oe47FaCmv7EeEsDXuCO7Ci5BJU/KZ9Z/00xw86mxV8OdsoFnfdv4P4tK/oucE7UMOj4DZDIPN2teGsB76PVARENjjXOWS2y+9sPnx80Hz6+oHzNbTYTrqh/oV01CsDNdfWOZvPgTfpr6eoBq1JH3n7u15UZBpQ4eTCLXaqP0Cbdx6qVEOxUv6VtF/ul6yIr62uBXWsvzmNyDD1uTgSdp1tOXJzW74iLPd3bFRCvxGO5ttCtAh4ZpXK2BpogDjIePr2B3XByj3LcS4ZjpHdr9AOC9oUYAZ4h58ccyXzNjeDo2uAmxR3lp+sOjzuWEboEd/fvYcT4YGfcaczimRr4PJZt7IBa8p6lWf+8YhWUzMHZLuYcZrHjr4YO8H0iEOsQGtdfLqogEC3JSDQeqpmm2tGgs6bIKGONzaN8ANZDo4IjqPn6EYISiFZ+ny9lokVtDxF46wiu3ReJlhQOLAJ5nzYIJu4ZZcGKjWnpXvy1mrrXWJJPpGDVWgRCjlX3HzFw1JQ6c3Q4yE+qYW0BxvaYB6wkjW9GBg=
  file:
  - build/megantory.linux
  - build/megantory.macos
  - build/megantory.exe
  on:
    tags: true
