language: go
env:
- GO111MODULE=on
deploy:
  provider: releases
  api_key:
    secure: '08h+sEdDK4yie+CTfTeusnZTak/Lo8AYV91b+BE0d23pQwI1mzBFXZqC2PBI8SptxYrpxLfHYLnq3ARydVpaIp3Lq8nGwCd2doj9UcQoL5PqTYC5qZkFuVu4bcpXL7vKnXD9WAADW6z+dFVRV5bhwYfbOqKHJSTdeMnUcQFfXcLJiNm/luBrIK994a7ms2jA8FHue4oMpqV/2FWViLzjkAZSuaOz88XDsc8Ravwg0yGPrBNl+DHiiKM9956CmL77NbIMe1u0+Fh4T1xPoIBO6PbKiS2dXTm8/RqC43KP2DylseK6b+8YouJ471fGZlD6Qp6RI9BnbR90+HA1ZGjvoVtvSdmhZe2L+9rgz7qWmAu/pjfq8Zg1Y/1MXw4j4leJ0R3QuKj6rGFebryUqt+yxT7iEyorAVmIQJ1Kla7JpjfNnwfAkEguY8p5sO2bv85MrjbMIH9sphQ1X0Q/W4mMWJs8Sp+lC/xmJeTpnB3NUtRsegGBkhU9ucuGczY/T1d5MPNFnJWAqtymflYyuGvah13rM0UBhdBz/MVgI81XVnPgVr/O0ANsmebJU17EZ26a/1z8DTq3fAoVv938rgVFnqCk+juEpPhaG7cVCrMEa/1oxFTI7n8XAWkRxi8BZDRZiPo0Gat+maYypaxlaRjcLf8SWAZc0VAfuhM7VwV37rE='
  file: build/*
  on:
    repo: Kaurin/megantory
    branch: cicd
    tags: true
