language: go
env:
- GO111MODULE=on
deploy:
  provider: releases
  skip_cleanup: true
  file: build/*
  user:
    secure:
      secure: 4vlIdg3TqPyOSMkN1LZN1DQsv2R1SKU4NMnNGnYYsNx5nfyHJEncSPG3ctRoPVVYQGg/RoKbr41ktzpy8xiP1VciBz5C0AuBbx7Hw5onbJwZLi9zKSerVko7SQgtr3gCg61t27rKzKRwyLJWPU+t2Dc7gjWb0oicqdBmIKXQ2gtt45N+4uorkv15pxwQJN3xm741G/brjyNRsaTlMfJgFoedfQ91shgTb/y3wUfDM0mzJqHwRtwybW/HQjPRVYBlbEyJF7o70Jt/xZGgAkv4cM80HD5bjC/BIRcPAk3PmOgmvr0zRXD0ehkmn/IpDSo1Fq/SUg007WJNnCx00o/Orr/xf3LoHO/F7pLXq0oBc9tmmYcuio+HEoItjqlXaJVVJVtPG8gshPKTzHqMT0a4IKTLOJwTnyAvBk3E/Wt1WnQp+Jw9kZepUX7sWQfE1KRPPlb0g32rETJdLllGL769EvzQ9WjYXgp7L9Us9v+IHBufTcUuwCRBF/9gUYzfCOoe2tbepju8lKy7qk9LXtI3gPa1qettU0slhVb7nuTsuv+NJF1MlKvyL9p3Bkfa8HJ7DdQ60U+Ri9azRewb9Rpk1j3ekZLALM/OFI37gRL39QvnYnMdA2Ybqig7EiKTlVxkmFe6yd828tA/uosUjDLHpcxeD7RB3/zXeQrm471v+jw=
  password:
    secure:
      secure: pS4N+winAANk1nXN1P1L6bKZbiolypR/iBTfqvKlqECCTjTWqlgLWZgpvCqD8u0SP3WZgMjmTs44SZTgyf+wG4TY4rPj10eNCsqCj2GLfyA/xGT30d6ISRSd0pQEx/tJVaFCsyBpkstECRlnqjAPt2Nn1Zex8O7Nb6EtHM18swjfvqSf+1yLtSH6qiV7Hi3LD5XK/iHNNNEA+cCSbuNJs24t1ipam4R8oRvw+gfMg+oTQohgYtxs1nn60XgL6kcWRcN1TgUxIVNk90QrE5SBy8tAUDSn1vOZqSkmf4NcZS7yePlxgWKLocn4GenbTITh7Ep4IZSFknMpwLrWF5rRMt3VgfI2Z1NSC8c1P7U4saWgC7ruZsSrkKk8F1wTvzUfB/R3flUd8I/JCSEE1H12DYMAtoaSuXtIvZXdPmMMJ4OOf5CqQ+Gkax66xEiTpz3vNmVBNm+oR4F/5Gwc/yxktBIZcWKqnI8+jlVvnPOQNmzkbAJpGU0wXxt/dnX0hiaOWfc9ZUPg4tq+0/49vxDrl0fYLAHhHZhP83vBClofwTM+YOlz9FKJk3Ac04PGRCLvHr+qf4xvgGo7hYxV68VTcTCS/HdPwPzUBP59t476bTRzrhH+qM2eWIlGZfrOo7LbkIFfRTMZ+WkRLTZhgS6kc/tcyQ7gjuLgMqDGutNS854=
  on:
    tags: true
    branch: cicd
