language: go
env:
  - GO111MODULE=on
deploy:
  provider: releases
  skip_cleanup: true
  file: build/*
  api_key:
    secure: 3oySuSQhqO+SCtDO3q3vPXYBqvlG/4yxJE5cK+EGQi+DJKTiZWXL0Qpxty9SzeqcM5Sm4sDAsRN/2v2CvNIh5E26PLLJPJml5SkfywjKb3+HcfmoqpykJV6YH18+6lY2lj4g2bIIbUYk8zXPZNeIX35BPqOwG4TumI+bJOdXaHLOUwVaYC4TLJj6rywTQAs19IqhxeWLKcBB50XXXx+d1L9G8PKVlRlKgy2XxvmxToX/aJ9rEm3UJ+NlAYSeeJwWSayxIDXMpiHy9MxhPcIkGzbNT5waspdI0dCa0glVkETEz8Y9kDV3iD2l8ZO5FzX3zQ4lFKsoWk93AA+4kK0CkU9ZdOg4SznrQUtH739/CZMLXLKUVwMBPbIBl/as21h3Un+T1NtsvSZX8wpf6beb6B3dzVvi98+HXj6k5l+s3gFc+Za06LoQOGgEXfmpCfYvdiLcqtgZ+I79E5IbMuI2pxaKuYKXLCGNr7rGJ636kilJk5nG/Ut92JdwN/OCIU3c+GDDbPFot/WlZ6m1F7GVQlCfor9D6y+K+S0N9mNnHp+xJz02C/cJr3PZSHY7J43vqdWuhx7Yh66/I8OvnNK3w1PkX7Kw42voOmvuwQBVNnvmzN/c2lmOOdnbz5XrN1FrPAacnTKSehTinjvg566e4r0fmz56Ixdz8rqSW7MroA4=
  on:
    tags: true
    branch: cicd
