language: go
env:
- GO111MODULE=on
deploy:
  provider: releases
  api_key:
    secure: o5a2JZ61l+KCpHacJnArKOAK+f9NQjigfqHcZwjUuWfBxDC2ODhHcjMErN3Q12G5/nQTx0J5onc1d8UWEpm+N+QNweMB6Nrrv6RhW7SwqBh/0Hd0DUcbBDngGkliXICJcE1EyyFQkUSPNa3JwzTGJ/7UYdpEh9ji8mMt8IZhxfJpad10678l+sKj3+R2H2mEk6hUnVqrvl1A4RWx1peeNWguMGUQT+/ULeBwb3TgZswHT3x/dlSbs+1RZZyYuHVASTSW+XWyssVHLWP+ffMh91rFc4+iAKCvI6e9aX2bB0+VGqwZkX9fAl+RMQe+F4zUs7GLDGdw5lgDFl6jlvubTWb/L4dtq8P4xvO1cJ5QwgL+NuFkSo0mgJyBP+0XeHxfN1RHWGe/3a3IvZibr+1HBx3/rmNKkCTdy2H/IQtZU/pARF9RM8v7P+b843KU/rc92A0yEcChUXc6Po5vtkbsf4tStFLIF4Wp/2Tj4PD4voTzsUUFvpogWT4MbHi5BwvR1CxuePcX/dBX1tzhV+GGpKv1U9PbBSq1+nmBB3GL6JH8+nE49ePVryv0AnR6Wm1T050DzkZK0IjFpCXOSRj8GzQoecftueRxNPYbYKIVG0luMDZujHPVB5cG1IDmYoWSJu2bOLxK2vSFTf6whjZbva4iccNcrXB9D4gVDRARl8k=
  file: builds/*
  on:
    repo: Kaurin/megantory
    branch: cicd

