language: go
env:
- GO111MODULE=on
deploy:
  provider: releases
  skip_cleanup: true
  file: build/*
  api_key:
    secure:
      secure: MV+xZbamYC+QHlYM5zcxi/2nbVib3nmuP+C1aedtcFjKkytzINeglMvFtuLGPM1cyOQ0KY9I1UobilE3eNFkR5yhOM0sZcBWSQHrAvH2L6u09FKFAdIzIf3fTpCAMrRn69eMCjhJXIdsKhdhOm2as81d/vcFSuUsTORpUh44fIjN7e/1y+a0jvzel3LHZLEXulNTseUtmlHf4zcWsQdJIR6fAX8fuE0uwcRdS0bfK0ApVpLjhk6zVOXN/3bqaboRoDOlVrJ1EQ+57HeDQsiyWiekul7FHuZp2qL7dkbDRL4PNX6g81PC/vxMPq3TF6sr2hehIT6YEFAnV4+b1SbJ0zRTGcoz1Q7MzX5vwcD5hy8eXqRFMtjwIJy02sLznMTlIfBWUAvUOY0g/wc/nuxUtzzq3S4FOWW8lHoCHH3UsFHOF2YdTRX9rufb99VocLjE4QNvz2ODafMf8Rxhndpt8Qs+vgE/2VN7ShH+iUIc9qsZY4CnkcGPnn4TkaPkYGgkc3eu0/jP78AJN7XkwNtCnuR/YQjwSAHcijsJsBQyekAg/aP6ySAh8EKPvjjo65YOfNTtDKHRbAgXfEzE6Z337Zr8o0FnphFa3YyH/p9gRpvPv1WN7vkphpBJRe2Bag0+pnQPFqbUqkihFIkp8LdYabwrjlNbAmp6Ar9Hvh1+5Y4=
  on:
    tags: true
    branch: cicd
